app_public:
    resource: "@AppPublicBundle/Resources/config/routing.yml"

app_admin:
    resource: "@AppAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

app_rest:
    resource: "@AppRestBundle/Resources/config/routing.yml"
    type:     rest
    prefix:   /api